version: '2'

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - app-tier
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - TZ=Asia/Seoul

  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - app-tier
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_HEAP_OPTS=-Xmx256m -Xms256m
      - TZ=Asia/Seoul

  mongo:
    container_name: 'local-mongo'
    image: 'mongo:latest'
    networks:
      - app-tier
    ports:
      - "27017:27017"
    environment:
      - TZ=Asia/Seoul

  api-gateway:
    container_name: 'api-gateway'
    image: 'isvara/api-gateway:1.1'
    networks:
      - app-tier
    ports:
    - "8080:8080"
    depends_on:
      - catalog
      - challenge
      - user
      - problem
    environment:
      - TZ=Asia/Seoul
      - CATALOG_SVC=http://catalog:8081
      - CHALLENGE_SVC=http://challenge:8082
      - USER_SVC=http://user:8083
      - PROBLEM_SVC=http://problem:8084
      - JWT_SECRET=testsecret
      - JWT.ISSUER=k-judge

  catalog:
    container_name: 'catalog'
    image: 'isvara/catalog-prod'
    networks:
      - app-tier
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - mongo
    environment:
      - DB_USERNAME="${DB_USERNAME}"
      - DB_PASSWORD="${DB_PASSWORD}"
      - DB_URL="${DB_URL}"
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MONGO_DB_HOST=mongo:27017
      - TZ=Asia/Seoul

  problem:
    container_name: 'problem'
    image: 'isvara/problem-prod'
    networks:
      - app-tier
    ports:
      - "8084:8084"
    depends_on:
      - kafka
    environment:
      - DB_USERNAME="${DB_USERNAME}"
      - DB_PASSWORD="${DB_PASSWORD}"
      - DB_URL="${DB_URL}"
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - TZ=Asia/Seoul

  challenge:
    container_name: 'challenge'
    image: 'isvara/challenge-prod'
    networks:
      - app-tier
    ports:
      - "8082:8082"
    depends_on:
      - kafka
    environment:
      - DB_USERNAME="${DB_USERNAME}"
      - DB_PASSWORD="${DB_PASSWORD}"
      - DB_URL="${DB_URL}"
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - CATALOG_SERVER=http://catalog:8081
      - TZ=Asia/Seoul

  user:
    container_name: 'user'
    image: 'isvara/user-prod'
    networks:
      - app-tier
    ports:
      - "8083:8083"
    environment:
      - DB_USERNAME="${DB_USERNAME}"
      - DB_PASSWORD="${DB_PASSWORD}"
      - DB_URL="${DB_URL}"
      - JWT_SECRET=testsecret
      - JWT.ISSUER=k-judge
      - JWT.DURATION_TIME=60000
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092