version: '2'

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - app-tier
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - TZ=Asia/Seoul

  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - app-tier
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_HEAP_OPTS=-Xmx256m -Xms256m
      - TZ=Asia/Seoul

  mongo:
    container_name: 'local-mongo'
    image: 'mongo:latest'
    networks:
      - app-tier
    ports:
      - "27017:27017"
    environment:
      - TZ=Asia/Seoul

  catalog:
    container_name: 'catalog'
    image: 'isvara/problem-catalog:1.0'
    networks:
      - app-tier
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - mongo
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MONGO_DB_HOST=mongo:27017
      - TZ=Asia/Seoul

  problem:
    container_name: 'problem'
    image: 'isvara/problem:1.0'
    networks:
      - app-tier
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - TZ=Asia/Seoul

  challenge:
    container_name: 'challenge'
    image: 'isvara/challenge:1.0'
    networks:
      - app-tier
    ports:
      - "8082:8082"
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - CATALOG_SERVER=http://catalog:8081
      - TZ=Asia/Seoul