server:
  port: 8080
  servlet:
    encoding:
      force: true
    context-path: /
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      INDENT_OUTPUT: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:challenge;MODE=MYSQL;DB_CLOSE_DELAY=-1